CREATE ROLE goblogs WITH CREATEDB LOGIN PASSWORD 'goblogs';

CREATE DATABASE goblogs OWNER = goblogs;
GRANT ALL PRIVILEGES ON DATABASE goblogs TO goblogs;

CREATE DATABASE tenant OWNER  = goblogs;
GRANT ALL PRIVILEGES ON DATABASE tenant TO goblogs;